### ISSUE TITLE
server stutters

### ISSUE THREAD

**Issue by haithem2459** [Lightman314/Lightmans-Discord-Integration#12]
https://spark.lucko.me/1iw9nhRA7H
Whenever I use anything to tp out of a chunk, it causes the server to rubberband for long periods of time.

**Comment by Lightman314** [comment]
Severe lag does tend to happen even in vanilla Minecraft when a player teleports, as the server now needs to load hundreds of chunks instantaneously due to the players new location... You're literally reporting a vanilla behavior as an issue caused by a mod that literally doesn't interact with players or the world in any way, shape, or form... All my mod does is listen to chat & log-in/out related forge events, and of course the relevant discord bot functionality/commands. It's physically impossible for my mod to contribute to this lag in any way, shape, and/or form...
