### ISSUE TITLE
Suggestion: Borrow Webhooks support from dcintegration

### ISSUE THREAD

**Issue by Anaerin** [Lightman314/Lightmans-Discord-Integration#3]
dcintegration (https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge) has the capability to use webhooks to communicate with Discord. This gives the ability for users to appear as themselves in Discord (As in, posts appear to come from a BOT account with their name, and with their headshot as the discord avatar). This makes interaction in Discord much cleaner, and makes it both easier to see server messages from chat, and to tell who is talking.

It also gives dcintegration the capability of listening for / commands inside Discord, rather than having to rely on ! commands being sent back and forth.

and dcintegration uses the MIT license, so you can borrow code from it as you like, provided you keep their usage notice intact.

**Comment by Anaerin** [comment]
Actually, the better URL is the DiscordIntegration-core repo, as that has the actual Discord code in it: https://github.com/ErdbeerbaerLP/DiscordIntegration-Core

**Comment by Lightman314** [comment]
I think I shall pass on this, as it will likely be a lot of work and frankly, I'm not all that familiar with how the discord API works. If you want me to straight up copy/paste a feature that another mod already has, you might as just use their mod instead of mine, or simply install both and only enable the features from my mod that you wish to use (such as the console channel, or the currency bot from LC, etc.). Granted using both would require everyone linking their account twice (once for their bot, once for my bot), but to be honest I don't really intend to continue adding features (especially a major update such as this one) to this mod/bot, as I have my hands full working on Lightman's Currency and LC Tech updates and issues.
