### ISSUE TITLE
Work with the Vanish mod

### ISSUE THREAD

**Issue by VirtualGaming1** [Lightman314/Lightmans-Discord-Integration#9]
So I notice that it dose not say that the player that gone into vanish, discord side dose not get the message like "VirtualGaming left the server" when in vanish. but on the server it dose say that on and also if a vanish player connects on the player the server will not say the player is joined until that player unvanish.

here is the link to the mod: https://www.curseforge.com/minecraft/mc-mods/vanishmod

**Comment by Lightman314** [comment]
Just so that I'm 100% clear on what I need to do here, I'm gonna outline my plans for the intended compatibility plans.

1- If a player joins or leaves the server while they're vanished, no discord announcement shall be made.
2- If a player vanishes or un-vanishes, a discord announcement shall be made that they left or re-joined the server.

Are there any other modifications I need to make, such as changes to how it gets the player count for the "There are X players online" status messages, or how it lists the players when the !list command is run?

Edit: Upon testing, I did indeed have to update how the player list is obtained, so vanished players will not appear when the !list command is run, nor will they be accounted for in the player count.

**Comment by Lightman314** [comment]
Added in v0.0.3.9.

**Comment by VirtualGaming1** [comment]
Sound good and thanks
